{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "56d18072-0ed4-4df8-946a-b3380b6d2cf0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Zelle 1: (optional) Abhängigkeiten installieren — nur ausführen, falls nötig\n",
    "# Führ diese Zelle nur einmal aus, wenn pandas oder ipywidgets fehlen.\n",
    "import sys\n",
    "!{sys.executable} -m pip install --quiet pandas ipywidgets || true"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d39edd59-3585-4969-ac0b-5806871a0156",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Datenverzeichnis: /home/wih42zor/campusEingang/campus_data\n",
      "ipywidgets verfügbar: True\n"
     ]
    }
   ],
   "source": [
    "# Zelle 2: Imports und Pfade vorbereiten\n",
    "import os\n",
    "import json\n",
    "from datetime import datetime, date\n",
    "import pandas as pd\n",
    "from IPython.display import display, HTML\n",
    "\n",
    "# Optional: ipywidgets (falls installiert)\n",
    "try:\n",
    "    import ipywidgets as widgets\n",
    "    WIDGETS_AVAILABLE = True\n",
    "except Exception:\n",
    "    WIDGETS_AVAILABLE = False\n",
    "\n",
    "DATA_DIR = os.path.join(os.getcwd(), \"campus_data\")\n",
    "os.makedirs(DATA_DIR, exist_ok=True)\n",
    "DATA_FILE = os.path.join(DATA_DIR, \"data.json\")\n",
    "SURVEY_FILE = os.path.join(DATA_DIR, \"survey.json\")\n",
    "\n",
    "print(\"Datenverzeichnis:\", DATA_DIR)\n",
    "print(\"ipywidgets verfügbar:\", WIDGETS_AVAILABLE)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "352e6d79-882e-4efc-855f-e813103805ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Datenverzeichnis: /home/wih42zor/campusEingang/campus_data\n"
     ]
    }
   ],
   "source": [
    "# Zelle 2: Imports und Pfade vorbereiten\n",
    "import os\n",
    "import json\n",
    "import tempfile\n",
    "from datetime import datetime, date\n",
    "from threading import Thread\n",
    "import pandas as pd\n",
    "\n",
    "# Datenverzeichnis im Notebook-Ordner (schreibbar) oder temporär\n",
    "DATA_DIR = os.path.join(os.getcwd(), \"campus_data\")\n",
    "os.makedirs(DATA_DIR, exist_ok=True)\n",
    "\n",
    "DATA_FILE = os.path.join(DATA_DIR, \"data.json\")\n",
    "SURVEY_FILE = os.path.join(DATA_DIR, \"survey.json\")\n",
    "\n",
    "print(\"Datenverzeichnis:\", DATA_DIR)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7f061a53-1cf0-4e12-afba-05278b6976e6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data files ready: True True\n"
     ]
    }
   ],
   "source": [
    "# Zelle 3: Beispiel-Daten, Lade-/Speicherfunktionen\n",
    "default_data = {\n",
    "    \"tasks\": [\n",
    "        {\"id\": 1, \"title\": \"Immatrikulation abschließen\", \"category\": \"Immatrikulation\",\n",
    "         \"deadline\": \"2026-10-01\", \"link\": \"https://uni.example/immatrikulation\", \"done\": False,\n",
    "         \"notes\": \"Unterlagen mitbringen\"},\n",
    "        {\"id\": 2, \"title\": \"Chipkarte abholen\", \"category\": \"Organisatorisch\",\n",
    "         \"deadline\": \"2024-01-01\", \"link\": \"\", \"done\": False, \"notes\": \"\"}\n",
    "    ],\n",
    "    \"next_id\": 3\n",
    "}\n",
    "\n",
    "def ensure_files():\n",
    "    if not os.path.exists(DATA_FILE):\n",
    "        with open(DATA_FILE, \"w\", encoding=\"utf-8\") as f:\n",
    "            json.dump(default_data, f, ensure_ascii=False, indent=2)\n",
    "    if not os.path.exists(SURVEY_FILE):\n",
    "        with open(SURVEY_FILE, \"w\", encoding=\"utf-8\") as f:\n",
    "            json.dump([], f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_data(path=DATA_FILE):\n",
    "    ensure_files()\n",
    "    with open(path, \"r\", encoding=\"utf-8\") as f:\n",
    "        return json.load(f)\n",
    "\n",
    "def save_data(data, path=DATA_FILE):\n",
    "    with open(path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(data, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "def load_survey(path=SURVEY_FILE):\n",
    "    ensure_files()\n",
    "    with open(path, \"r\", encoding=\"utf-8\") as f:\n",
    "        return json.load(f)\n",
    "\n",
    "def save_survey(entries, path=SURVEY_FILE):\n",
    "    with open(path, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(entries, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "ensure_files()\n",
    "print(\"Data files ready:\", os.path.exists(DATA_FILE), os.path.exists(SURVEY_FILE))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "42a03f77-1596-42d2-8cfe-3599e09ecd78",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>title</th>\n",
       "      <th>category</th>\n",
       "      <th>deadline</th>\n",
       "      <th>done</th>\n",
       "      <th>overdue</th>\n",
       "      <th>notes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>Chipkarte abholen</td>\n",
       "      <td>Organisatorisch</td>\n",
       "      <td>2024-01-01</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>Immatrikulation abschließen</td>\n",
       "      <td>Immatrikulation</td>\n",
       "      <td>2026-10-01</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>Unterlagen mitbringen</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>jdc</td>\n",
       "      <td>All</td>\n",
       "      <td>2026</td>\n",
       "      <td>False</td>\n",
       "      <td>False</td>\n",
       "      <td>jsv</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id                        title         category    deadline   done  \\\n",
       "0   2            Chipkarte abholen  Organisatorisch  2024-01-01  False   \n",
       "1   1  Immatrikulation abschließen  Immatrikulation  2026-10-01  False   \n",
       "2   3                          jdc              All        2026  False   \n",
       "\n",
       "   overdue                  notes  \n",
       "0     True                         \n",
       "1    False  Unterlagen mitbringen  \n",
       "2    False                    jsv  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Zelle 4: Hilfsfunktionen für Analyse (DataFrame, Overdue-Berechnung, Anzeige)\n",
    "def tasks_to_df(data):\n",
    "    df = pd.DataFrame(data[\"tasks\"])\n",
    "    if df.empty:\n",
    "        df = pd.DataFrame(columns=[\"id\",\"title\",\"category\",\"deadline\",\"link\",\"done\",\"notes\"])\n",
    "    if \"deadline\" not in df.columns:\n",
    "        df[\"deadline\"] = \"\"\n",
    "    def parse_deadline(s):\n",
    "        try:\n",
    "            return datetime.strptime(s, \"%Y-%m-%d\").date()\n",
    "        except:\n",
    "            return None\n",
    "    df[\"deadline_date\"] = df[\"deadline\"].apply(parse_deadline)\n",
    "    today = date.today()\n",
    "    df[\"overdue\"] = df.apply(lambda r: (not bool(r.get(\"done\"))) and (r[\"deadline_date\"] is not None) and (r[\"deadline_date\"] < today), axis=1)\n",
    "    df = df.sort_values(by=[\"overdue\", \"deadline_date\"], ascending=[False, True])\n",
    "    return df\n",
    "\n",
    "def show_tasks_table(df):\n",
    "    if df.empty:\n",
    "        display(HTML(\"<p><em>Keine Aufgaben vorhanden.</em></p>\"))\n",
    "    else:\n",
    "        display(df[[\"id\",\"title\",\"category\",\"deadline\",\"done\",\"overdue\",\"notes\"]].reset_index(drop=True))\n",
    "\n",
    "# Beispiel: lade und zeige aktuelle Tabelle\n",
    "data = load_data()\n",
    "df = tasks_to_df(data)\n",
    "show_tasks_table(df)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0d1be79d-fc7d-4a68-8dd6-62dc72a88086",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Zelle 5: CRUD-Funktionen (zum interaktiven Verwenden im Notebook)\n",
    "def add_task(title, category=\"All\", deadline=\"\", link=\"\", notes=\"\"):\n",
    "    data = load_data()\n",
    "    nid = data.get(\"next_id\", 1)\n",
    "    task = {\"id\": nid, \"title\": title, \"category\": category, \"deadline\": deadline, \"link\": link, \"notes\": notes, \"done\": False}\n",
    "    data[\"tasks\"].append(task)\n",
    "    data[\"next_id\"] = nid + 1\n",
    "    save_data(data)\n",
    "    return task\n",
    "\n",
    "def edit_task(task_id, **kwargs):\n",
    "    data = load_data()\n",
    "    task = next((t for t in data[\"tasks\"] if t[\"id\"]==task_id), None)\n",
    "    if not task:\n",
    "        raise ValueError(\"Task not found\")\n",
    "    for k,v in kwargs.items():\n",
    "        if k in task:\n",
    "            task[k] = v\n",
    "    save_data(data)\n",
    "    return task\n",
    "\n",
    "def toggle_done(task_id):\n",
    "    data = load_data()\n",
    "    task = next((t for t in data[\"tasks\"] if t[\"id\"]==task_id), None)\n",
    "    if not task:\n",
    "        raise ValueError(\"Task not found\")\n",
    "    task[\"done\"] = not task.get(\"done\", False)\n",
    "    save_data(data)\n",
    "    return task\n",
    "\n",
    "def delete_task(task_id):\n",
    "    data = load_data()\n",
    "    data[\"tasks\"] = [t for t in data[\"tasks\"] if t[\"id\"]!=task_id]\n",
    "    save_data(data)\n",
    "    return True\n",
    "\n",
    "# Beispiele (ausführen, um zu testen)\n",
    "# add_task(\"Prüfungsanmeldung\", \"Prüfungen\", \"2026-09-15\", \"https://uni.example/pruefungen\", \"Anmeldeportal nutzen\")\n",
    "# toggle_done(1)\n",
    "# edit_task(2, title=\"Chipkarte abholen (aktualisiert)\")\n",
    "# delete_task(99)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "17b1035c-9568-41ee-aba1-c41745a9337b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Überfällige Aufgaben: 1\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>title</th>\n",
       "      <th>category</th>\n",
       "      <th>deadline</th>\n",
       "      <th>notes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Chipkarte abholen</td>\n",
       "      <td>Organisatorisch</td>\n",
       "      <td>2024-01-01</td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id              title         category    deadline notes\n",
       "1   2  Chipkarte abholen  Organisatorisch  2024-01-01      "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Offene Aufgaben insgesamt: 3\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>title</th>\n",
       "      <th>category</th>\n",
       "      <th>deadline</th>\n",
       "      <th>overdue</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Chipkarte abholen</td>\n",
       "      <td>Organisatorisch</td>\n",
       "      <td>2024-01-01</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Immatrikulation abschließen</td>\n",
       "      <td>Immatrikulation</td>\n",
       "      <td>2026-10-01</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>jdc</td>\n",
       "      <td>All</td>\n",
       "      <td>2026</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id                        title         category    deadline  overdue\n",
       "1   2            Chipkarte abholen  Organisatorisch  2024-01-01     True\n",
       "0   1  Immatrikulation abschließen  Immatrikulation  2026-10-01    False\n",
       "2   3                          jdc              All        2026    False"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Anzahl Aufgaben pro Kategorie:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>count</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>category</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>All</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Immatrikulation</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Organisatorisch</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 count\n",
       "category              \n",
       "All                  1\n",
       "Immatrikulation      1\n",
       "Organisatorisch      1"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Zelle 6: Nützliche Analyse-Queries (ausführen, um Ergebnisse zu sehen)\n",
    "data = load_data()\n",
    "df = tasks_to_df(data)\n",
    "\n",
    "# 1) Alle überfälligen Aufgaben\n",
    "df_overdue = df[df[\"overdue\"]]\n",
    "print(\"Überfällige Aufgaben:\", len(df_overdue))\n",
    "display(df_overdue[[\"id\",\"title\",\"category\",\"deadline\",\"notes\"]])\n",
    "\n",
    "# 2) Offene Aufgaben (nicht erledigt)\n",
    "df_open = df[~df[\"done\"]]\n",
    "print(\"Offene Aufgaben insgesamt:\", len(df_open))\n",
    "display(df_open[[\"id\",\"title\",\"category\",\"deadline\",\"overdue\"]])\n",
    "\n",
    "# 3) Anzahl pro Kategorie\n",
    "print(\"Anzahl Aufgaben pro Kategorie:\")\n",
    "display(df.groupby(\"category\").size().sort_values(ascending=False).rename(\"count\").to_frame())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e4b729e-1a10-4a27-bcea-e6a7829fe3e7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7a853cf0-9eaa-4466-af4f-f64b0046245c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bfecdcf239374c5b9d1e96e7a2f8ced8",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "VBox(children=(Text(value='', description='Titel:', layout=Layout(width='60%')), Text(value='All', description…"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Zelle 7: Optional interaktive UI mit ipywidgets (nur wenn ipywidgets installiert ist)\n",
    "if WIDGETS_AVAILABLE:\n",
    "    # Widgets definieren\n",
    "    title_w = widgets.Text(description=\"Titel:\", layout=widgets.Layout(width=\"60%\"))\n",
    "    category_w = widgets.Text(description=\"Kategorie:\", value=\"All\")\n",
    "    deadline_w = widgets.Text(description=\"Frist (YYYY-MM-DD):\", value=\"\")\n",
    "    link_w = widgets.Text(description=\"Link:\", value=\"\")\n",
    "    notes_w = widgets.Textarea(description=\"Notizen:\", layout=widgets.Layout(width=\"60%\", height=\"80px\"))\n",
    "    add_btn = widgets.Button(description=\"Aufgabe hinzufügen\", button_style=\"success\")\n",
    "    output = widgets.Output()\n",
    "\n",
    "    def on_add_clicked(b):\n",
    "        with output:\n",
    "            try:\n",
    "                task = add_task(title_w.value.strip() or \"Neue Aufgabe\", category_w.value.strip() or \"All\",\n",
    "                                deadline_w.value.strip(), link_w.value.strip(), notes_w.value.strip())\n",
    "                print(\"Hinzugefügt:\", task[\"id\"], task[\"title\"])\n",
    "                # clear inputs\n",
    "                title_w.value = \"\"\n",
    "                category_w.value = \"\"\n",
    "                deadline_w.value = \"\"\n",
    "                link_w.value = \"\"\n",
    "                notes_w.value = \"\"\n",
    "            except Exception as e:\n",
    "                print(\"Fehler:\", e)\n",
    "            # show updated table\n",
    "            data = load_data()\n",
    "            df = tasks_to_df(data)\n",
    "            display(df[[\"id\",\"title\",\"category\",\"deadline\",\"done\",\"overdue\"]])\n",
    "\n",
    "    add_btn.on_click(on_add_clicked)\n",
    "\n",
    "    # Anzeige-Layout\n",
    "    form = widgets.VBox([title_w, category_w, deadline_w, link_w, notes_w, add_btn, output])\n",
    "    display(form)\n",
    "else:\n",
    "    print(\"ipywidgets nicht installiert. Installiere mit: pip install ipywidgets\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "1ed312fe-6b39-43a0-baf7-5e8752dc17fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Zelle 8: Umfrage-Funktionen (Pain Points) und Anzeige\n",
    "def add_survey_entry(name, problem, urgency=\"Mittel\"):\n",
    "    entries = load_survey()\n",
    "    entry = {\"name\": name.strip(), \"problem\": problem.strip(), \"urgency\": urgency, \"time\": datetime.now().strftime(\"%Y-%m-%d %H:%M\")}\n",
    "    entries.insert(0, entry)\n",
    "    save_survey(entries)\n",
    "    return entry\n",
    "\n",
    "def show_survey():\n",
    "    entries = load_survey()\n",
    "    if not entries:\n",
    "        display(HTML(\"<p><em>Noch keine Umfrageeinträge.</em></p>\"))\n",
    "    else:\n",
    "        html = \"<ul>\"\n",
    "        for e in entries:\n",
    "            html += f\"<li><strong>{e.get('name') or 'Anonym'}</strong> ({e.get('urgency')}) — {e.get('problem')} <span style='color:#666;font-size:0.9em'>[{e.get('time')}]</span></li>\"\n",
    "        html += \"</ul>\"\n",
    "        display(HTML(html))\n",
    "\n",
    "# Beispiel: add_survey_entry(\"Max\", \"Unklare Prüfungsanmeldung\", \"Hoch\")\n",
    "# show_survey()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
